/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICourseCertificate,
  ICourseCertificateInterface,
} from "../../../contracts/Courses.sol/ICourseCertificate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "courseId",
        type: "string",
      },
    ],
    name: "mintCertificate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICourseCertificate__factory {
  static readonly abi = _abi;
  static createInterface(): ICourseCertificateInterface {
    return new Interface(_abi) as ICourseCertificateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICourseCertificate {
    return new Contract(address, _abi, runner) as unknown as ICourseCertificate;
  }
}
