/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coursesSol from "./Courses.sol";
export type { coursesSol };
export type { CourseCertificate } from "./CourseCertificate";
export type { Exchange } from "./Exchange";
export type { YDToken } from "./YDToken";
